<?xml version="1.0"?>
<package format="2">
  <name>dx_data_collector_msgs</name>
  <version>0.0.0</version>
  <description>Messages for dx_data_collector</description>

  <maintainer email="maintainers@example.com">RIOS AI</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>std_msgs</depend>
  <build_depend>message_generation</build_depend>
  <build_export_depend>message_generation</build_export_depend>
  <exec_depend>message_runtime</exec_depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
