VERSION 0.6
FROM github.com/rios-ai/<internal_build_framework>+rios-ros


copy-source:
    FROM +dep-setup

save-source:
  LOCALLY
  SAVE ARTIFACT ../../ local_source

dep-setup:
    FROM +custom-dependencies
    DO github.com/rios-ai/<internal_build_framework>+PULL_DEPS --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH

ros-setup:
    FROM +copy-source
    RUN --no-cache echo "=== Invalidating the cache ==="
    DO github.com/rios-ai/<internal_build_framework>+BUILD_ROS_WORKSPACE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH

tag-image: # Use the shared Tag Image code
    FROM +ros-setup
    ARG CURRENT_DATETIME
    ARG CURRENT_REPO
    ARG CURRENT_BRANCH
    ARG CURRENT_COMMIT_HASH
    ARG CURRENT_TAG=latest

    LABEL buildtime=$CURRENT_DATETIME

    DO github.com/rios-ai/<internal_build_framework>+TAG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

# Custom dependencies needed for this specific ROS Node
custom-dependencies:
    FROM +base

    WORKDIR /opt/rios/src

    # Uncomment if you wish to copy source from your repository into the RIOS ROS Workspace overlay
    # As-is this copies the root directory of your repo directly to /opt/rios/src
    COPY +save-source/local_source /opt/rios/src/

    # Use these files as needed; if you don't need them, feel free to remove from the repo / Earthfile
    # COPY apt-packages.txt .
    COPY ros-blacklist.txt .
    COPY submodules.repos .
