VERSION 0.7

IMPORT --allow-privileged github.com/rios-ai/<internal_build_framework> AS RIOS
IMPORT --allow-privileged github.com/rios-ai/<internal_build_framework>/ros1 AS ROS1

FROM RIOS+rios-ros

ARG DEV_ENV=false --global

# Custom dependencies needed for this specific ROS Node
custom-dependencies:
    FROM +base
    WORKDIR /opt/rios/src

    # Use these files as needed; if you don't need them, feel free to remove from the repo / Earthfile
    # The build will install dependencies using these files prior to building your ROS Workspace
    #COPY ros-blacklist.txt .
    #COPY requirements.txt .
    COPY apt-packages.txt .
    COPY submodules.repos .

# Build step saves the source code to an artifact for copying into the image (+copy-source step)
save-source:
    LOCALLY
    SAVE ARTIFACT ../ local_source

# Build step copies the saved source code into the image
copy-source:
    FROM +custom-dependencies
    # Uncomment if you wish to copy source from your repository into the RIOS ROS Workspace overlay
    # As written this copies the root directory of your repo directly to /opt/rios/src
    COPY +save-source/local_source /opt/rios/src/dx_data_collector

# Build step for pulling dependencies
dep-setup:
    FROM +copy-source

    DO RIOS+RECURSIVE_PULL_DEPS
    DO +ADD_AWS_CPP_SDK
    DO ROS1+CATKIN_CREATE

copy-build:
    FROM +dep-setup
    
    WAIT
      # Build the project
      BUILD +build
    END

    # Copy build output
    COPY +build/install /opt/rios/install
    IF [ "$DEV_ENV" = "true" ]
      COPY +build/devel /opt/rios/devel
      COPY +build/build /opt/rios/build
      COPY +build/src /opt/rios/src
    END

build:
    FROM +dep-setup

    # Build your ros workspace
    DO ROS1+CATKIN_BUILD --CACHED=$DEV_ENV

unit-test:
    FROM +build
    DO ROS1+CATKIN_TEST --TEST_TYPE=unit  

integration-test:
    FROM +build
    DO ROS1+CATKIN_TEST --TEST_TYPE=integration

dev-environment:
    FROM +copy-build
    
    ARG DEV_ENV=false
    ARG USERNAME
    
    IF [ "$DEV_ENV" = "true" ]
        DO RIOS+SETUP_DEV_ENV --USERNAME=$USERNAME
    END

# These local commands generate the branch/commit/repo information for tagging the image
build-envs:
    LOCALLY

    RUN mkdir -p build-envs
    RUN basename `git rev-parse --show-toplevel` | tr '[:upper:]' '[:lower:]' >> build-envs/CURRENT_REPO
    RUN git rev-parse --abbrev-ref HEAD | sed 's/\//_/g' >> build-envs/CURRENT_BRANCH
    RUN git log --pretty=format:"%h" -1 >> build-envs/CURRENT_COMMIT_HASH 

    SAVE ARTIFACT ./build-envs/

    RUN rm -rf build-envs

tag-image: # Use the shared Tag Image code
    FROM +dev-environment

    COPY +build-envs/build-envs /tmp/build-envs
    
    ARG CURRENT_TAG=latest
    ARG CURRENT_REPO=$(cat /tmp/build-envs/CURRENT_REPO)
    ARG CURRENT_BRANCH=$(cat /tmp/build-envs/CURRENT_BRANCH)
    ARG CURRENT_COMMIT_HASH=$(cat /tmp/build-envs/CURRENT_COMMIT_HASH)

    RUN rm -rf /tmp/build-envs
        
    ARG CURRENT_DATETIME=$(date +"%s")
    LABEL buildtime=$CURRENT_DATETIME

    DO RIOS+TAG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

    # -debug image builds
    DO RIOS+ADD_DEVTOOLS
    DO RIOS+TAG_DEBUG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

ADD_AWS_CPP_SDK:
    COMMAND
    WORKDIR /opt/rios

    RUN /bin/bash -c "git clone --depth 1 --branch 1.11.260 --recurse-submodules https://github.com/aws/aws-sdk-cpp \
                      && mkdir sdk_build \
                      && cd sdk_build \
                      && cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY=\"s3\" \
                      && make \
                      && make install \
                      && cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY=\"transfer\" \
                      && make \
                      && make install"
