VERSION 0.7

IMPORT --allow-privileged github.com/rios-ai/<internal_build_framework> AS RIOS
IMPORT --allow-privileged github.com/rios-ai/<internal_build_framework>/ros1 AS ROS1

ARG --global DEV_ENV=false
ARG BASE_IMAGE=RIOS+rios-ros

FROM $BASE_IMAGE

# Custom dependencies needed for this specific ROS Node
custom-dependencies:
    FROM +base
    WORKDIR /opt/rios/src

    # Use these files as needed; if you don't need them, feel free to remove from the repo / Earthfile
    # The build will install dependencies using these files prior to building your ROS Workspace
    #COPY ros-blacklist.txt .
    #COPY requirements.txt .
    COPY apt-packages.txt .
    COPY submodules.repos .

# Build step saves the source code to an artifact for copying into the image (+copy-source step)
save-source:
    ARG CACHE_BUSTER

    LOCALLY
    SAVE ARTIFACT ../ local_source_${CACHE_BUSTER}

# Build step copies the saved source code into the image
copy-source:
    FROM +custom-dependencies
    ARG CACHE_BUSTER

    IF [ -z "$CACHE_BUSTER" ]
        # This is to workaround the bug described in https://github.com/earthly/earthly/issues/1076
        RUN echo "CACHE_BUSTER must be set as --CACHE_BUSTER=$RANDOM when calling the build command." && exit 1
    END

    # Uncomment if you wish to copy source from your repository into the RIOS ROS Workspace overlay
    # As written this copies the root directory of your repo directly to /opt/rios/src
    COPY +save-source/local_source_${CACHE_BUSTER} /opt/rios/src/dx_data_collector

# Build step for pulling dependencies
dep-setup:
    FROM +copy-source

    DO RIOS+RECURSIVE_PULL_DEPS
    DO +ADD_INTEL_HARDWARE_ENCODING
    DO +ADD_AWS_CPP_SDK
    DO ROS1+CATKIN_CREATE

copy-build:
    FROM +dep-setup

    WAIT
      # Build the project
      BUILD +build
    END

    # Copy build output
    COPY +build/install /opt/rios/install
    IF [ "$DEV_ENV" = "true" ]
      COPY +build/devel /opt/rios/devel
      COPY +build/build /opt/rios/build
      COPY +build/src /opt/rios/src
    END

build:
    FROM +dep-setup

    # Build your ros workspace
    DO ROS1+CATKIN_BUILD --CACHED=$DEV_ENV

unit-test:
    FROM +dep-setup
    DO ROS1+CATKIN_TEST --TEST_TYPE=unit

integration-test:
    FROM +dep-setup

    ARG DISABLE_SYSMON="OFF"

    DO ROS1+CATKIN_TEST --TEST_TYPE=integration --CATKIN_BUILD_ARGS="-DDUMMY=${DISABLE_SYSMON}"

dev-environment:
    FROM +copy-build

    ARG DEV_ENV=false
    ARG USERNAME

    IF [ "$DEV_ENV" = "true" ]
        DO RIOS+SETUP_DEV_ENV --USERNAME=$USERNAME
    END

# These local commands generate the branch/commit/repo information for tagging the image
build-envs:
    LOCALLY

    RUN mkdir -p build-envs
    RUN basename `git rev-parse --show-toplevel` | tr '[:upper:]' '[:lower:]' >> build-envs/CURRENT_REPO
    RUN git rev-parse --abbrev-ref HEAD | sed 's/\//_/g' >> build-envs/CURRENT_BRANCH
    RUN git log --pretty=format:"%h" -1 >> build-envs/CURRENT_COMMIT_HASH

    SAVE ARTIFACT ./build-envs/

    RUN rm -rf build-envs

# Create a base image with all dependencies installed without building the src code.
tag-base-image:
    ARG ROS_VERSION=noetic

    FROM +copy-source
    DO RIOS+RECURSIVE_PULL_DEPS
    DO ROS1+CATKIN_ROSDEPS --ROS_VERSION=${ROS_VERSION}
    DO +ADD_INTEL_HARDWARE_ENCODING
    DO +ADD_AWS_CPP_SDK

    # Remove src used for installing dependencies.
    WORKDIR /opt/rios
    RUN rm -rf /opt/rios/src

    COPY +build-envs/build-envs /tmp/build-envs

    ARG CURRENT_TAG=latest

    # Base image tags are suffixed with -base
    ARG CURRENT_REPO=$(cat /tmp/build-envs/CURRENT_REPO)-base
    ARG CURRENT_BRANCH=$(cat /tmp/build-envs/CURRENT_BRANCH)
    ARG CURRENT_COMMIT_HASH=$(cat /tmp/build-envs/CURRENT_COMMIT_HASH)

    RUN rm -rf /tmp/build-envs

    ARG CURRENT_DATETIME=$(date +"%s")
    LABEL buildtime=$CURRENT_DATETIME

    DO RIOS+TAG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

tag-image: # Use the shared Tag Image code
    FROM +dev-environment

    COPY +build-envs/build-envs /tmp/build-envs

    ARG CURRENT_TAG=latest
    ARG CURRENT_REPO=$(cat /tmp/build-envs/CURRENT_REPO)
    ARG CURRENT_BRANCH=$(cat /tmp/build-envs/CURRENT_BRANCH)
    ARG CURRENT_COMMIT_HASH=$(cat /tmp/build-envs/CURRENT_COMMIT_HASH)

    RUN rm -rf /tmp/build-envs

    ARG CURRENT_DATETIME=$(date +"%s")
    LABEL buildtime=$CURRENT_DATETIME

    DO RIOS+TAG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

    # -debug image builds
    DO RIOS+ADD_DEVTOOLS
    DO RIOS+TAG_DEBUG_IMAGE --BRANCH=$CURRENT_BRANCH --REPO=$CURRENT_REPO --COMMIT=$CURRENT_COMMIT_HASH --TAG=$CURRENT_TAG

ADD_AWS_CPP_SDK:
    COMMAND
    WORKDIR /opt/rios

    IF ldconfig -p | grep -q libaws-cpp-sdk
        RUN echo "=== libaws-cpp-sdk is already installed. ===";
    ELSE
        RUN echo "=== libaws-cpp-sdk not found, installing ===";
        RUN /bin/bash -c "git clone --depth 1 --branch 1.11.260 --recurse-submodules https://github.com/aws/aws-sdk-cpp \
                        && mkdir sdk_build \
                        && cd sdk_build \
                        && cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY=\"s3\" -DENABLE_TESTING=OFF \
                        && make \
                        && make install \
                        && cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY=\"transfer\" -DENABLE_TESTING=OFF \
                        && make \
                        && make install \
                        && ldconfig"
    END

ADD_INTEL_HARDWARE_ENCODING:
    COMMAND
    RUN /bin/bash -c "sudo apt-get -q install -y gpg-agent wget && \
                      wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | \
                      sudo gpg --yes --dearmor --output /usr/share/keyrings/intel-graphics.gpg && \
                      echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu focal-legacy main' | \
                      sudo tee  /etc/apt/sources.list.d/intel.gpu.focal.list && \
                      sudo apt-get -q update && \
                      sudo apt-get -q install -y \
                      intel-opencl-icd \
                      intel-level-zero-gpu level-zero \
                      intel-media-va-driver-non-free libmfx1 libmfxgen1 libvpl2 libvpl-dev"

    WORKDIR /opt/rios

    IF command -v ffmpeg >/dev/null 2>&1
        RUN echo -e "=== ffmpeg is already installed, version $(ffmpeg -version | head -n 3) \n    ===";
    ELSE
        RUN echo "=== ffmpeg not found, installing ===";
        RUN /bin/bash -c "wget https://ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz && \
                        tar -xf ffmpeg-7.0.1.tar.xz && \
                        cd ffmpeg-7.0.1 && \
                        ./configure --enable-libvpl --enable-nonfree --enable-static --disable-shared --enable-libx264 --enable-gpl &&\
                        make && \
                        sudo make install"
    END
