<?xml version="1.0"?>
<package format="2">
  
  <name>dx_data_collector_commander</name>
  <version>0.0.1</version>
  <description>RIOS interface for data collection</description>

  <maintainer email="maintainers@example.com">RIOS AI</maintainer>

  <license>Apache-2.0</license>

  <author>Leo Keselman</author>
  <author>Carlos Fernandez-Martinez</author>

  <buildtool_depend>catkin</buildtool_depend>
  
  <depend>roscpp</depend>
  <depend>dx_data_collector_msgs</depend>
  <depend>dx_rios_utils</depend>
  <depend>dx_rios_pybind</depend>
  
</package>
