<?xml version="1.0"?>
<package format="2">
  <name>dx_subsystem</name>
  <version>0.0.1</version>
  <description>SUBSYSTEM DESCRIPTION</description>

  <!-- One maintainer tag required, multiple allowed, one person per tag -->
  <maintainer email="leo.keselman@rios.ai">Leo Keselman</maintainer>
  <maintainer email="chris.keraly@rios.ai">Chris Keraly</maintainer>

  <license>Proprietary</license>

  <author email="leo.keselman@rios.ai">Leo Keselman</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>dx_subsystem_msgs</depend>
  <depend>dx_sysmon_sdk</depend>
  <depend>std_msgs</depend>

</package>
