apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dx-data-collector.fullname" . }}
  labels:
    {{- include "dx-data-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dx-data-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: dx-data-collector
        {{- include "dx-data-collector.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: dx-data-collector
          image: {{ .Values.dockerRegistry }}/dx_data_collector:{{ .Values.containerTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: ["/bin/bash", "-c", "roslaunch dx_data_collector dx_data_collector.launch \
                                       data_collection_config:=/data-collector/data_collection_config.yaml
                                       node_name:={{ .Values.collectorName }} --wait  2>&1 | \
                                       rotatelogs -e -l '/logs/data_collector_%Y-%m-%d_%H-%M-%S.log' {{ .Values.logSize }}"]
          env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/vault/secrets/wasabi-access.yaml"
            - name: ROS_MASTER_URI
              value: {{ printf "http://%s:%v/" (coalesce .Values.hostname (printf "%s-rios-roscore-service" .Release.Name)) (.Values.port | default 80) }}
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RIOS_SUBSYSTEM_TYPE
              value: dx-data-collector
            - name: RIOS_SUBSYSTEM_INSTANCE
              value: {{ include "dx-data-collector.name" . }}
            # - name: LIBVA_DRIVERS_PATH
            #   value: /usr/lib/x86_64-linux-gnu/dri
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
          - name: log-storage
            mountPath: /logs
          - name: core-dump-storage
            mountPath: /core-dump
          - name: data-collector-config
            mountPath: /data-collector/
            readOnly: false
          - name: fs-output-dir
            mountPath: /data-collector-fs-data/
            readOnly: false
          startupProbe:
            exec:
              command:
              - sh
              - -c
              - 'curl -f --header "subsystem-type: $RIOS_SUBSYSTEM_TYPE" --header "subsystem-instance: $RIOS_SUBSYSTEM_INSTANCE" {{ .Values.sysmon_probes.host }}:{{ .Values.sysmon_probes.port }}{{ .Values.sysmon_probes.paths.startup }}'
            initialDelaySeconds: {{.Values.StartupInitialDelay}}
            periodSeconds: {{.Values.StartupInitialPeriod}}
            failureThreshold: {{.Values.StartupFailureThreshold}}
            successThreshold: {{.Values.StartupSuccessThreshold}}
            timeoutSeconds: {{.Values.StartupTimeoutSeconds}}
          {{ if .Values.LivenessProbeEnable }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - 'curl -f --header "subsystem-type: $RIOS_SUBSYSTEM_TYPE" --header "subsystem-instance: $RIOS_SUBSYSTEM_INSTANCE" {{ .Values.sysmon_probes.host }}:{{ .Values.sysmon_probes.port }}{{ .Values.sysmon_probes.paths.liveness }}'
            initialDelaySeconds: {{.Values.LivenessInitialDelay}}
            periodSeconds: {{.Values.LivenessInitialPeriod}}
            failureThreshold: {{.Values.LivenessFailureThreshold}}
            successThreshold: {{.Values.LivenessSuccessThreshold}}
            timeoutSeconds: {{.Values.LivenessTimeoutSeconds}}
          {{- end }}

      volumes:
        - name: log-storage
          hostPath:
            path: {{ .Values.logPath }}/{{ include "dx-data-collector.fullname" . }}
            type: DirectoryOrCreate
        - name: core-dump-storage
          hostPath:
            path: {{ .Values.coreDumpPath }}/{{ include "dx-data-collector.fullname" . }}
            type: DirectoryOrCreate
        - name: data-collector-config
          configMap:
            name: {{ include "dx-data-collector.fullname" . }}-config
        - name: fs-output-dir
          hostPath:
            path: {{ .Values.fsOutputDir }}
            type: DirectoryOrCreate
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
