# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1


# Set to override CNI ROS master interface
hostname:
port:

dockerRegistry: "<internal_registry>"
containerTag: develop
collectorName: dx_data_collector
imagePullPolicy: IfNotPresent

logPath: "/data-pool/logs"
coreDumpPath: "/data-pool/core-dump"
logSize: 50M # Apache rotatelogs maximum filesize, followed by exactly one of the letters B (Bytes), K (KBytes), M (MBytes) or G (GBytes).

#startup probe parameters
StartupInitialDelay: 5
StartupInitialPeriod: 3
StartupFailureThreshold: 100
StartupSuccessThreshold: 1
StartupTimeoutSeconds: 2

#liveness probe parameters
LivenessInitialDelay: 5
LivenessInitialPeriod: 3
LivenessFailureThreshold: 100
LivenessSuccessThreshold: 1
LivenessTimeoutSeconds: 2

env:
  PYTHONUNBUFFERED: 1
  ROSCONSOLE_STDOUT_LINE_BUFFERED: 1

resources:
  limits:
    cpu: 30
    memory: 48Gi
  requests:
    cpu: 2
    memory: 12Gi

configs: {}
nameOverride: ""
fullnameOverride: ""
fsOutputDir: /data-pool/bags # Where to output filesystem data on host machine

# These values specify how to assign this deployment to a k3s Node
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - headnode

# Sysmon health (default) probes configuration
sysmon_probes:
  host: "rios-dx-sysmon-service"
  port: 31415
  paths:
    startup: "/rios/sysmon/healthprobe/startup"
    liveness: "/rios/sysmon/healthprobe/liveness"
    readiness: 
