

template_checker:
  type: template_checker
  alarm:
    description: Some random error
    severity: error
    period: 1.
    period_tolerance: 0.5
  settings:
    normal_percentage: 97


template_checker2:
  type: template_checker2
  alarm:
    description: Some other randm error
    severity: warn
    period: 1.
    period_tolerance: 0.5


