name: dx_data_collector - Build

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'main'
      - 'develop'
  schedule:
    - cron: '0 16 * * 6' # Run every Sat at 4pm UTC
jobs:
  build:
    uses: ./.github/workflows/rios_build.yaml
    with:
      working-directory: '.'
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      bot-token: ${{ secrets.RIOS_BOT_TOKEN }}
