name: dx_data_collector - Build

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'main'
      - 'develop'
  schedule:
    - cron: '0 16 * * 6' # Run every sat at 4pm UTC

jobs:
  build:
    uses: rios-ai/<internal_workflow_templates>/.github/workflows/rios_build.yaml@develop
    with:
      working-directory: .
      earthly-args: '--BASE_IMAGE=<internal_registry>/dx_data_collector-base:develop'
    secrets:
      ssh-key: ${{ secrets.CI_SSH_KEY }}
      bot-token: ${{ secrets.RIOS_BOT_TOKEN }}
