apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dx-subsystem.fullname" . }}
  labels:
    {{- include "dx-subsystem.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dx-subsystem.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: dx-subsystem
        {{- include "dx-subsystem.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: dx-subsystem
          image: {{ .Values.dockerRegistry }}/dx_subsystem_template-dx_subsystem:{{ .Values.containerTag }}
          args: ["/bin/bash", "-c", "roslaunch dx_subsystem dx_subsystem.launch config_file:=/subsystem/subsystem_config.yaml --wait"]
          env:
            - name: ROS_MASTER_URI
              value: http://{{ .Release.Name}}-rios-roscore-service:80/
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          volumeMounts:
          - name: subsystem-config
            mountPath: /subsystem/subsystem_config.yaml
            subPath: subsystem_config.yaml
            readOnly: false
      volumes:
        - name: subsystem-config
          configMap:
            name: {{ include "dx-subsystem.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
